spring.application.name=JavaMailSender

spring.datasource.url=jdbc:postgresql://localhost:5432/spring_test
spring.datasource.username=postgres
spring.datasource.password=030730

# Gmail SMTP Server Settings
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ditor879@gmail.com
spring.mail.password=epjnyscnsyjcniud

# Protocol Properties
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.debug=true